
server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/customer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:9999


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

